name = "My Little Modpack Development Hell"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4961ea657443649b08267d0d54e9005e54df394d0a4d7cfd65f24da7f4e3b83c"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
