name = "My Little Modpack Development Hell"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e296b795dc334cee54b28f2f90bd1492a34d2714602f91697e6e78ece4012a69"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
