name = "Computer Pack"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f65d2494fab108b7233e0d5a7115975213f21ccf055cb47dbd4e1eb88442748e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
