name = "Computer Pack"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e664ed02ed66530cf8849c2322b023553245b70507715c3bce237bdc1bc2019"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
