name = "The Sky Belongs to Me"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a96369d1e040944e4d1752f4a9e30e8eba934d49c9934cc5c592456d7e614b5"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.5"
