name = "The Sky Belongs to Me"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a2570c6e9eeba3268edeb0af6df4f66b143b544b5065e70c56b4a24c24e39a7"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.5"
