name = "Futuristic Industrialism"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b523b14f4759af57d2722c9944a3b1f2ddb1ba10d15fa1b0deede3fba0ebf20"

[versions]
fabric = "0.14.18"
minecraft = "1.19.3"
