name = "Futuristic Industrialism"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "756416bdf7f9f8b60ce3a48fafa2b6582d732cfc0c5b09ee889cca5324d8cf49"

[versions]
fabric = "0.14.18"
minecraft = "1.19.3"
