name = "Futuristic Industrialism"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33a4fab9773f75a20b4a68306ae6dc58d393ad30e3eb75c3312ea9dbe40bbc79"

[versions]
fabric = "0.14.18"
minecraft = "1.19.3"
