name = "Topac"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c289840596ae9d211767b00ac0c0aae0e6093142278d1b2f8dc2a687463813b"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
