name = "Topac"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23ede1f6f9ff188362f2cc271dd78275c4ee1905d458f36d1dde07bb21323fd1"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
