name = "Topac"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c70093913dc0df43cef203b89254134d9d846f7f84124ff24eea7d36550c82e6"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
