name = "Topac"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2c4dfc93932e0693caeb6b3e4f334dd9c177495ca1fbc79ee1eba9610cbf67e"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
