name = "Topac"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fddcceb0e84adb3eec1e5d19986cc1972cbd8c46cca4830ad19e93c087e79a03"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
