name = "Topac"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa37ea54a7cc1e80ccc6717d7044635a3603a6bf92e02995b949d360558fd775"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
