name = "Who are you"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "218832eba311d5944145ef23c9d3134ad4437bec7682862e1983aa924839cffb"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
