name = "Who are you"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f97d6e7cb62cddcc060ebaff2eacb367cb0ee934d387a0ca5ea5a8ec9a6ed89"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
