name = "Who are you"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05f3affea5f42bf5190520b1eabbb9b113d626ff8223f904a0db23e5be9f06fa"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
