name = "Who are you"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c73885f865104226d4bbad483d0a31185f6e6f8a475db9a83e9968f4c663d3d"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
