name = "Who are you"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7193ca7c16158c9251dd0c76994b06f30618903bfe2f29540fb65dd0b5e3627"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"
