name = "War Games"
author = "Blue"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d0f85011e3b12751a872a244acc47898ea788ad8603d2752d66f07db8acf209"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
