name = "War Games"
author = "Blue"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06aca3e5d457f35058c2198bea1904e150c198074e83162ffc82e5cbc0218fbf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
