name = "STEM"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a966cddf5b3f3e034cc98e96281339cfd4df1e69d284158288c3d85fb4a0a0d8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
