name = "Radioactive Wasteland"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbfb3665be3930220c282f114117622de1399395eb28f1c485b36bb9ad4231b3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
