name = "Radioactive Wasteland"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e610af8e9211cb05666f6b28a40413c4cdde7e9d92e3d1ce9a38d73b4abe3095"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
