name = "Radioactive Wasteland"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "541f2fdfd2455b8005dfcc80248c1175e50f6de29239e5fb1a2dff83ad054b25"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
