name = "Radioactive Wasteland"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aabf0516c6f91c28d4a84540a4c96b19dee11c9a431ba0a58a46c2290107fda9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
