name = "Fabric Ambience"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e943c3f5707ffe90f2f7157e36bb3ce35fe182ad04ef4b59e7449ed162603a97"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
