name = "Battle Royale"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2670cd7811f5362e76246b45d33d0c072fd51946f9a7c0b0644f7ed072cad053"

[versions]
forge = "47.2.18"
minecraft = "1.20.1"
