name = "Low Tech"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3614de46bdfa8bef8e655be5ddd928d8ad18b2208c2e3bd5d13eea46084c9072"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
