name = "Low Tech"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4608e474629716e26b7e8e321c361deb0c1e5bec6103ee6fb614b86712aefb3b"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
