name = "Low Tech"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a56bdb3f027604103d60feb7482180dff316954324649d21ea3db9b84c7f53a1"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
