name = "Low Tech"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c902143a57f1b5c55fd3f607f751bc6cc9dba0d5b0eaed62e7c4fb068ae83fa3"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
