name = "Low Tech"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bec18f2a3e7e07468caf52445b3621e168a67fab27836a901ae2e63f69b7a3ab"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
