name = "Low Tech"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b178aa22c57da650b5df1e77579af666a22cb2a2bbf1570b3feeb1f4fa1846b"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
