name = "Performance Optimizations"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66f4a2a18c9aa10fb5497a59d479d555b201ac5bdc2bbc90980ba02a1c734d91"

[versions]
fabric = "0.14.17"
minecraft = "1.19.4"
