mods.ItemStages.stageModItems("machine", "immersiveengineering");
mods.ItemStages.stageModItems("machine", "immersivepetroleum");
mods.ItemStages.stageModItems("atomic", "icbmclassic");
mods.ItemStages.stageModItems("atomic", "nuclearcraft");
mods.ItemStages.stageModItems("atomic", "trinity");
mods.ItemStages.stageModItems("space", "ic2");
mods.ItemStages.stageModItems("space", "advancedrocketry");
mods.ItemStages.stageModItems("information", "opencomputers");
mods.ItemStages.stageModItems("information", "computronics");