name = "Samtech"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdbca15c9a43c49561af05a386f20a1cff34f4171ea59f24005c13d8dbda28e7"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
