name = "Samtech"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7954c1610b6793f9f73465809500b38cc892ab2ba9bbeb7d7e96047e25b7fee"

[versions]
forge = "47.2.30"
minecraft = "1.20.1"
