name = "Yet Another Worldgen Pack"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e162f144512c72d183c39d538418bc92451e73240cbc0a2e44ee7010d99748e0"

[versions]
fabric = "0.15.1"
minecraft = "1.19.3"
