name = "Kpack"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cd0eb73b1ed3197ab6f3045689e9e843648c28024a3922ee01e881eb3fda7b8"

[versions]
minecraft = "1.21"
quilt = "0.27.0-beta.1"
