name = "Kpack"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ba33024b1dcf7be1ca0a37a88ebda74ac6922887ab3ba1a8e701c6b44a04649"

[versions]
minecraft = "1.21"
quilt = "0.27.0-beta.1"
