name = "Kpack"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7874cae9ed5f8735a00d3f05bfd5a58ea85deb42da669aaa3853faafca8706f"

[versions]
minecraft = "1.21"
quilt = "0.27.0-beta.1"
