name = "Ultimate Kitchen Sink of Ultimate Destiny"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fe3faad02c95116823f1712f7d5b0e47f6e64e75e2e5c9b50bdf61eb96c4113"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
