name = "Ultimate Kitchen Sink of Ultimate Destiny"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "678f08877f51a8c0b7442ec27b1d8a1f54fdb863155148ef96dd80bed2d0adf6"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
