name = "Ultimate Kitchen Sink of Ultimate Destiny"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "361500494f0af45b8df92f2df54af8bdd1eb46220978dc068cb6e0fa7f27e8d5"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
