name = "Time"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e24adccd5c1a719805c2d75d60154e14659d24b688e5e7a9c594ed18c7a889d7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
