name = "Exploration 1.20"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d35989a285aefea0a57ae99688edfbc7f18e8dc183f737cbbbec1daaea4ebc9b"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
