name = "Exploration 1.20"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea430a7eb0ead3092ce5d4af1f058d103e83aa9631b96244eb0b6ce195e1deb2"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
