name = "Go Down Low (on me)"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81b7b64f1720e05ec2c7c1fd389792b7eb43ff60dd28ab55618523faabe78773"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
