name = "Go Down Low (on me)"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4672c83f7fc12b12e107bf6da566e5eaf7fa1561236845e5116be21db3ff9867"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
