name = "Go Down Low (on me)"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5793296bcdf8b87d73377ce14cf0c265c2e75cabc014a2ff28d2d071f98eb56"

[versions]
forge = "40.2.2"
minecraft = "1.18.2"
