name = "Simple Magic"
author = "Blue"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe5b1529f7a30b8bedf75842e8e0aace16aa9f33190ae8f45c8f466ff1df5d4d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
