name = "Hexing Beginnings"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e3d9de28af569f57121101807e77d562e3e509b2d134bf1d88eead63f2ff0b1"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
