name = "Hexing Beginnings"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55e8b21200e3a5bfbdfd13e004805d2c9d6d8fd0711288339dc1d4de99c52c99"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
