name = "Hexing Beginnings"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61fdfb4c956bae75e1afef064908d25231999a2891e3559cb75134f791dacdd1"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
