name = "Hexing Beginnings"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "baaa03dd46bc501d8ca0af2e571385cf93bdbcb6c9d54d3d577ebb7281b666a7"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
