name = "Hexing Beginnings"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1ec0b5d0bc23a75409c54427e1571119d970ad2bfb67102d31763e3f12d6975"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
