name = "Hexing Beginnings"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfe0a71ef4d7f3fd0506cf7e6b1209f1807bd2705e20c8613d890f7fa4eb6f73"

[versions]
minecraft = "1.19.2"
quilt = "0.26.1-beta.1"
