name = "Robtech"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17bedf2b1994d2d764547aae9680ba8a8c3d73b935d5cc2603854429ca78fc81"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
