name = "Robtech"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67da003014fc9fbe38b50afa95b496bdf9ecc04c0fa1c50e72e30a303501432c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
