name = "Robtech"
author = "Susul"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c21558c090c434a84a21d8a5ea56f6f22ef9046bbe895f69229fb87cd973167f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
