name: Build MultiMC instances
on: push
jobs:
  create-zips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "packwiz/packwiz-installer-bootstrap"
        latest: true
        fileName: "packwiz-installer-bootstrap.jar"
    - run: |
        for pack in */
        do
          NAME=$(cat $pack"pack.toml" | head -n 1 | cut -c 9- | rev | cut -c 2- | rev)
          mkdir "$NAME"
          mkdir "$NAME"/.minecraft
          cp packwiz-installer-bootstrap.jar "$NAME"/.minecraft
          printf "ForgeVersion=\nInstanceType=OneSix\nIntendedVersion=\nJoinServerOnLaunch=false\nLWJGLVersion=\nLiteloaderVersion=\nLogPrePostOutput=true\nMCLaunchMethod=LauncherPart\nManagedPack=false\nManagedPackID=\nManagedPackName=\nManagedPackType=\nManagedPackVersionID=\nManagedPackVersionName=\nOverrideCommands=true\nOverrideConsole=false\nOverrideGameTime=false\nOverrideJavaArgs=false\nOverrideJavaLocation=false\nOverrideMCLaunchMethod=false\nOverrideMemory=false\nOverrideNativeWorkarounds=false\nOverrideWindow=false\nPostExitCommand=\nPreLaunchCommand="\$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://susul-1312.github.io/minecraft-modpacks/$pack""pack.toml\nWrapperCommand=\niconKey=default\nlastLaunchTime=1669563250850\nname=$NAME\nnotes=" > "$NAME"/instance.cfg
          zip -r "$NAME".zip "$NAME"
        done
    - run: pwd
    - uses: actions/upload-artifact@v3
      with:
        path: /*.zip
