name: Build MultiMC instances
on: push
jobs:
  create-zips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "packwiz/packwiz-installer-bootstrap"
        latest: true
        fileName: "packwiz-installer-bootstrap.jar"
    - run: |
        for pack in */
        do
          NAME=$(cat $pack/pack.toml | head -n 1 | cut -c 9- | rev | cut -c 2- | rev)
          mkdir "$NAME"
          mkdir "$NAME"/.minecraft
          cp packwiz-installer-bootstrap.jar "$NAME"/.minecraft
          cat > "$NAME"/instance.cfg < "ForgeVersion=
          InstanceType=OneSix
          IntendedVersion=
          JoinServerOnLaunch=false
          LWJGLVersion=
          LiteloaderVersion=
          LogPrePostOutput=true
          MCLaunchMethod=LauncherPart
          ManagedPack=false
          ManagedPackID=
          ManagedPackName=
          ManagedPackType=
          ManagedPackVersionID=
          ManagedPackVersionName=
          OverrideCommands=true
          OverrideConsole=false
          OverrideGameTime=false
          OverrideJavaArgs=false
          OverrideJavaLocation=false
          OverrideMCLaunchMethod=false
          OverrideMemory=false
          OverrideNativeWorkarounds=false
          OverrideWindow=false
          PostExitCommand=
          PreLaunchCommand="$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://susul-1312.github.io/minecraft-modpacks/$pack/pack.toml
          WrapperCommand=
          iconKey=default
          lastLaunchTime=1669563250850
          name=$NAME
          notes="
        done
    - run: find -name '*.cfg' | xargs cat
