name: Build MultiMC instances
on: push
jobs:
  create-zips:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "packwiz/packwiz-installer-bootstrap"
        latest: true
        fileName: "packwiz-installer-bootstrap.jar"
    - run: |
        for pack in */
        do
          NAME=$(cat $pack"pack.toml" | head -n 1 | cut -c 9- | rev | cut -c 2- | rev)
          mkdir "$NAME"
          mkdir "$NAME"/.minecraft
          cp packwiz-installer-bootstrap.jar "$NAME"/.minecraft
          cat >> "$NAME"/instance.cfg << "a
          EOF"
        done
    - run: find -name '*.cfg' | xargs cat
